name: Framacraft
version: '0.0.1'
main: fr.nirbose.framacraft.Framacraft
api-version: 1.18
description: Framework for spigot plugin
commands:
  framacmd:
    description: framacmd
    usage: /framacmd
